version: "3.8"

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - timescale-data:/var/lib/postgresql/data
    networks:
      - quix-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - quix-network

  api:
    image: api-gate
    container_name: api-gate-quix
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - timescaledb
    networks:
      - quix-network

  db:
    image: db-quix
    container_name: db-quix
    depends_on:
      - redis
      - timescaledb
    networks:
      - quix-network

  engine:
    image: engine-quix
    container_name: engine-quix
    depends_on:
      - redis
      - timescaledb
    networks:
      - quix-network

  mm:
    image: mm-quix
    container_name: mm-quix
    depends_on:
      - redis
      - timescaledb
    networks:
      - quix-network

  ws-exchange:
    image: exchange-ws
    container_name: ws-quix
    ports:
      - "8081:8081"
    depends_on:
      - redis
      - timescaledb
    networks:
      - quix-network

volumes:
  timescale-data:

networks:
  quix-network:
    driver: bridge
